//
// Created by dany on 11/10/19.
//

#ifndef DATA_STRUCTURES_PROJECT_UCLA_DCYT_VVEHICULO_H
#define DATA_STRUCTURES_PROJECT_UCLA_DCYT_VVEHICULO_H


class VVehiculo {

};


#endif //DATA_STRUCTURES_PROJECT_UCLA_DCYT_VVEHICULO_H
