//
// Created by dany on 11/10/19.
//

#ifndef DATA_STRUCTURES_PROJECT_UCLA_DCYT_MVEHICULO_H
#define DATA_STRUCTURES_PROJECT_UCLA_DCYT_MVEHICULO_H


class MVehiculo {

};


#endif //DATA_STRUCTURES_PROJECT_UCLA_DCYT_MVEHICULO_H
